pipelines:
  - name: pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: kaloula.jfrog-pipelines.com/docker-local/dbp  # replace with your image path and name
          dockerImageTag: 1
